import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: "#f9f9ff",
          dim: "#cfdaf2",
          bright: "#f9f9ff",
          "container-lowest": "#ffffff",
          "container-low": "#f0f3ff",
          container: "#e7eeff",
          high: "#dee8ff",
          highest: "#d8e3fb",
        },
        "on-surface": "#111c2d",
        "on-surface-variant": "#424754",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        outline: "#727785",
        "outline-variant": "#c2c6d6",
        "surface-tint": "#005ac2",
        primary: {
          DEFAULT: "#0058be",
          foreground: "#ffffff",
          container: "#2170e4",
          "on-container": "#fefcff",
          fixed: "#d8e2ff",
          "fixed-dim": "#adc6ff",
          "on-fixed": "#001a42",
          "on-fixed-variant": "#004395",
        },
        "inverse-primary": "#adc6ff",
        secondary: {
          DEFAULT: "#505f76",
          foreground: "#ffffff",
          container: "#d0e1fb",
          "on-container": "#54647a",
          fixed: "#d3e4fe",
          "fixed-dim": "#b7c8e1",
          "on-fixed": "#0b1c30",
          "on-fixed-variant": "#38485d",
        },
        tertiary: {
          DEFAULT: "#006947",
          foreground: "#ffffff",
          container: "#00855b",
          "on-container": "#f5fff6",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          "on-fixed": "#002113",
          "on-fixed-variant": "#005236",
        },
        error: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
          container: "#ffdad6",
          "on-container": "#93000a",
        },
        "surface-variant": "#d8e3fb",
        background: "#f9f9ff",
        "on-background": "#111c2d",
        paper: "#ffffff",
        canvas: "#f9fafb",
        divider: "#f1f5f9",
        slate: {
          50: "#f9fafb",
          100: "#f0f3ff",
          200: "#e7eeff",
          300: "#dee8ff",
          400: "#d8e3fb",
          500: "#c2c6d6",
          600: "#727785",
          700: "#424754",
          800: "#263143",
          900: "#111c2d",
        },
      },
      fontFamily: {
        heading: ["var(--font-geist)", "ui-sans-serif", "system-ui"],
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui"],
        clinical: ["var(--font-inter)", "ui-serif", "Georgia"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "32px",
        gutter: "24px",
        "section-gap": "48px",
        "stack-sm": "12px",
        "stack-md": "20px",
      },
      boxShadow: {
        "elevation-1": "0 0 0 1px #e2e8f0",
        "elevation-2": "0px 4px 12px rgba(17, 28, 45, 0.03)",
        "elevation-3": "0px 20px 25px -5px rgba(17, 28, 45, 0.1), 0px 8px 10px -6px rgba(17, 28, 45, 0.04)",
        "elevation-inset": "inset 0 1px 0 0 rgba(255,255,255,0.6)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
